Make fancy bashrc.

diff --git a/linux/bashrc b/linux/bashrc
--- a/linux/bashrc
+++ b/linux/bashrc
@@ -1,1 +1,96 @@
+echo " ____               _      _____    _____";
+echo "|  _ \             | |    |  __ \  / ____|";
+echo "| |_) |  __ _  ___ | |__  | |__) || |";
+echo "|  _ <  / _\` |/ __|| '_ \ |  _  / | |";
+echo "| |_) || (_| |\__ \| | | || | \ \ | |____";
+echo "|____/  \__,_||___/|_| |_||_|  \_\ \_____|";
+echo;
 
+#-------------------------------------------------------------
+# Colors
+#-------------------------------------------------------------
+
+# Normal Colors
+Black='\e[0;30m'        # Black
+Red='\e[0;31m'          # Red
+Green='\e[0;32m'        # Green
+Yellow='\e[0;33m'       # Yellow
+Blue='\e[0;34m'         # Blue
+Purple='\e[0;35m'       # Purple
+Cyan='\e[0;36m'         # Cyan
+White='\e[0;37m'        # White
+
+# Bold
+BBlack='\e[1;30m'       # Black
+BRed='\e[1;31m'         # Red
+BGreen='\e[1;32m'       # Green
+BYellow='\e[1;33m'      # Yellow
+BBlue='\e[1;34m'        # Blue
+BPurple='\e[1;35m'      # Purple
+BCyan='\e[1;36m'        # Cyan
+BWhite='\e[1;37m'       # White
+
+# Background
+On_Black='\e[40m'       # Black
+On_Red='\e[41m'         # Red
+On_Green='\e[42m'       # Green
+On_Yellow='\e[43m'      # Yellow
+On_Blue='\e[44m'        # Blue
+On_Purple='\e[45m'      # Purple
+On_Cyan='\e[46m'        # Cyan
+On_White='\e[47m'       # White
+
+NC="\e[m"               # Color Reset
+
+ALERT=${BWhite}${On_Red} # Bold White on red background
+
+#-------------------------------------------------------------
+# Greetings and promt
+#-------------------------------------------------------------
+PS1="[${On_Blue}\W${NC}]\$ "
+echo -e "${BYellow}${USER}${NC}@${BCyan}${HOSTNAME}${NC}, in ${BBlue}`pwd`${NC}, on ${BPurple}`date '+%A %d-%b-%Y, %H:%M:%S'`${NC}"
+echo -e "${BRed}Dont rush, think twice!${NC}"
+
+#-------------------------------------------------------------
+# Aliases
+#-------------------------------------------------------------
+# Git
+alias gs='git status'
+alias gpl='git pull'
+alias gps='git push'
+alias glog='git log --oneline'
+alias ga='git add'
+alias gc='git commit'
+
+# Listing
+alias ll='ls -la'
+
+#-------------------------------------------------------------
+# Functions
+#-------------------------------------------------------------
+function extract() {
+    if [ -f $1 ] ; then
+        case $1 in
+            *.tar.bz2)   tar xvjf $1     ;;
+            *.tar.gz)    tar xvzf $1     ;;
+            *.bz2)       bunzip2 $1      ;;
+            *.rar)       unrar x $1      ;;
+            *.gz)        gunzip $1       ;;
+            *.tar)       tar xvf $1      ;;
+            *.tbz2)      tar xvjf $1     ;;
+            *.tgz)       tar xvzf $1     ;;
+            *.zip)       unzip $1        ;;
+            *.Z)         uncompress $1   ;;
+            *.7z)        7z x $1         ;;
+            *)           echo "'$1' cannot be extracted via >extract<" ;;
+        esac
+    else
+        echo "'$1' is not a valid file!"
+    fi
+}
+
+# Creates an archive (*.tar.gz) from given directory.
+function maketar() { tar cvzf "${1%%/}.tar.gz"  "${1%%/}/"; }
+
+# Create a ZIP archive of a file or folder.
+function makezip() { zip -r "${1%%/}.zip" "$1" ; }
